server:
  port: 3000
  session_secret: "3a9f8b2e5c1d7e6f4a0b9c8d2e5f1a3c7b6d8e9f0a1b2c3d4e5f6a7b8c9d0e1f"
  system_name: "HX"
  gin_mode: "debug"
  jwt_secret: "e5c1d7e6f4a0b9c8d2e5f1a3c7b6d8e9f0a1b2c3d4e5f6a7b8"
  frontend_base_url: "http://localhost:3000"
  theme: "defalut"
rate_limit:
  global_api_rate_limit_num: 1000
  global_api_rate_limit_duration: 60
  global_web_rate_limit_num: 500
  global_web_rate_limit_duration: 60
  upload_rate_limit_num: 10
  upload_rate_limit_duration: 60
  download_rate_limit_num: 10
  download_rate_limit_duration: 60
  critical_rate_limit_num: 5
  critical_rate_limit_duration: 60
  rate_limit_key_expiration_duration: "1m"

general:
  initial_root_token: "initial_root_token_value"
  initial_root_access_token: "initial_root_access_token_value"
  memory_cache_enabled: true
  debug_enabled: false
  only_one_log_file: true

redis:
  redis_conn_string: ""
  redis_password: ""
  database: 0
  redis_master_name: "mymaster"
  sync_frequency: "5m"

database:
  dsn: ""
  sql_max_idle_conns: 10
  sql_max_open_conns: 100
  sql_max_lifetime: 3600
  is_master_node: true
  debug_sql_enabled: false
  sqlite_path: "db.sqlite3"
  sqlite_busy_timeout: 5000
  using_sqlite: false
  using_postgresql: false
  using_mysql: false

mail:
  provider: "smtp"
  smtp_account: "account@example.com"
  smtp_token: "smtp_token_value"
  smtp_server: "smtp.example.com"
  smtp_port: 587
  smtp_from: "noreply@example.com"

logger:
  log_dir: "logs"
  only_one_log_file: false
  debug_enabled: false
  use_zap: true
