system:
  system_name: "HX"
  server_address: "http://localhost:3000"
  footer: ""
  logo: ""
  top_up_link: ""
  chat_link: ""
  quota_per_unit: 500000.0
  display_in_currency_enabled: true
  display_token_stat_enabled: true
  # 新增维护模式相关配置
  maintenance_mode_enabled: false
  maintenance_mode_message: ""
  # 新增公告配置
  announcement_enabled: false
  announcement_content: ""
  announcement_background_color: ""
  announcement_text_color: ""
  # 新增服务条款和隐私政策链接
  terms_of_service_link: ""
  privacy_policy_link: ""
  theme: "default"

server:
  address: "0.0.0.0"        # 服务器监听地址
  port: 3000
  mode: "release"           # 可选值：debug, release

session:
  session_secret: "3a9f8b2e5c1d7e6f4a0b9c8d2e5f1a3c7b6d8e9f0a1b2c3d4e5f6a7b8c9d0e1f"
  cookie_name: "session_id"
  cookie_domain: ""
  cookie_path: "/"
  cookie_secure: false
  cookie_http_only: true
  max_age: 3600             # 单位秒

redis:
  redis_conn_string: ""
  redis_password: ""
  redis_master_name: ""
  sync_frequency: "600"     # 注意：该字段类型为 string
  database: 0

authentication:
  password_login_enabled: true
  password_register_enabled: true
  email_verification_enabled: false
  github_oauth_enabled: false
  oidc_enabled: false
  wechat_auth_enabled: false
  turnstile_check_enabled: false
  register_enabled: true
  email_domain_restriction_enabled: false
  email_domain_whitelist:
    - "gmail.com"
    - "163.com"
    - "126.com"
    - "qq.com"
    - "outlook.com"
    - "hotmail.com"
    - "icloud.com"
    - "yahoo.com"
    - "foxmail.com"
  jwt_secret: "your_jwt_secret_here"   # 请替换为实际密钥
  jwt_expiration: 3600                 # 单位秒
  login_failures_lockout_enabled: false
  max_login_failures: 5
  lockout_duration: 15                 # 单位分钟

debug:
  debug_enabled: false
  debug_sql_enabled: false
  memory_cache_enabled: false
  enable_profiling: false
  profiling_port: 6060

smtp:
  smtp_server: ""
  smtp_port: 587
  smtp_account: ""
  smtp_from: ""
  smtp_token: ""
  enable_tls: false
  tls_skip_verify: false

oauth:
  github_client_id: ""
  github_client_secret: ""
  lark_client_id: ""
  lark_client_secret: ""
  oidc_client_id: ""
  oidc_client_secret: ""
  oidc_well_known: ""
  oidc_authorization_endpoint: ""
  oidc_token_endpoint: ""
  oidc_userinfo_endpoint: ""
  google_client_id: ""
  google_client_secret: ""
  google_redirect_url: ""

wechat:
  wechat_server_address: ""
  wechat_server_token: ""
  wechat_account_qr_code_image_url: ""
  wechat_app_id: ""
  wechat_app_secret: ""

message:
  message_pusher_address: ""
  message_pusher_token: ""
  telegram_bot_token: ""
  telegram_chat_id: ""
  slack_webhook_url: ""
  discord_webhook_url: ""

turnstile:
  turnstile_site_key: ""
  turnstile_secret_key: ""

quota:
  quota_for_new_user: 0
  quota_for_inviter: 0
  quota_for_invitee: 0
  quota_remind_threshold: 1000
  pre_consumed_quota: 500
  invite_code_length: 6      # 新增邀请码长度

sync:
  sync_frequency: 600

rate_limit:
  global_api_rate_limit_num: 480
  global_api_rate_limit_duration: 180
  global_web_rate_limit_num: 240
  global_web_rate_limit_duration: 180
  upload_rate_limit_num: 10
  upload_rate_limit_duration: 60
  download_rate_limit_num: 10
  download_rate_limit_duration: 60
  critical_rate_limit_num: 20
  critical_rate_limit_duration: 1200
  rate_limit_key_expiration_duration: "20m"
  ip_rate_limit_enabled: false
  ip_rate_limit_num: 100
  ip_rate_limit_duration: 60

metric:
  enable_metric: false
  metric_queue_size: 10
  metric_success_rate_threshold: 0.8
  metric_success_chan_size: 1024
  metric_fail_chan_size: 128
  prometheus_enabled: false
  prometheus_listen_address: ":9090"

relay:
  relay_timeout: 0
  relay_proxy: ""
  user_content_request_proxy: ""
  user_content_request_timeout: 30
  api_request_timeout: 30
  stream_request_timeout: 30
  model_mapping_enabled: false
  model_mapping: {}                   # 根据实际需要填写映射关系
  channel_mapping_enabled: false
  channel_mapping: {}
  completion_params_mapping_enabled: false
  completion_params_mapping: {}

general:
  initial_root_token: ""
  initial_root_access_token: ""
  gemini_version: "v1"
  only_one_log_file: false
  root_user_email: ""
  is_master_node: true
  time_zone: "UTC"
  default_language: "en"

log:
  log_level: "info"
  log_path: "./logs"
  log_filename: "app.log"
  max_size: 100             # 单位 MB
  max_backups: 7
  max_age: 30               # 单位天
  compress: false
  enable_console: true

database:
  options: ""
  using_sqlite: false
  using_postgresql: false
  using_mysql: false
  sqlite_path: "hx.db"
  sqlite_busy_timeout: 3000

payment:
  enabled: false
  type: "stripe"            # 可选：alipay, stripe 等
  api_key: ""
  secret_key: ""
  webhook_url: ""
  return_url: ""
  notify_url: ""
  product_name: ""

test:
  test_prompt: "Output only your specific model name with no additional text."
